CC = clang
CFLAGS = -Wall -Werror -g

all: swap

swap: swap.c
	$(CC) $(CFLAGS) -o swap swap.c

##############################################################################

clean:
	rm -rf swap *.dSYM
